######## Style #######
Style/MutableConstant:
  Exclude:
    - 'app/models/user.rb'

Style/LineEndConcatenation:
  Exclude:
    - 'db/seeds.rb'

# bin/rails generate rspec:install 時の生成ファイルでの違反。重要な情報があるかもしれないのでExclude
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

######## Rails ########
Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

# パスワード＆その確認の認証ができないなどの理由で、使わざるを得ない
Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/user.rb'
    - 'app/controllers/password_resets_controller.rb'
    - 'spec/helpers/session_helper.rb'
    - 'spec/requests/password_reset_requests_spec.rb'

####### Metrics #######

####### Layout ########

# privateメゾッドはインデントを通常より深くしたい
Layout/AccessModifierIndentation:
  Exclude:
    - 'app/controllers/users_controller.rb'
    - 'app/models/user.rb'
    - 'app/controllers/password_resets_controller.rb'

# privateメゾッドはインデントを通常より深くしたい
Layout/IndentationConsistency:
  Exclude:
    - 'app/controllers/users_controller.rb'
    - 'app/models/user.rb'
    - 'app/controllers/password_resets_controller.rb'

# 公式(github)に載っているpagy.rbのデフォルトに合わせる。
Layout/EmptyLines:
  Exclude:
    - 'config/initializers/pagy.rb'

####### Naming ##############
Naming/PredicateName:
  Exclude:
    - 'spec/support/test_helper.rb'
