######## Style #######
Style/MutableConstant:
  Exclude:
    - 'app/models/user.rb'

# bin/rails generate rspec:install 時の生成ファイルでの違反。重要な情報があるかもしれないのでExclude
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

######## Rails ########
Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

# パスワード＆その確認の認証ができないので、使わざるを得ない
Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/user.rb'
    - 'app/controllers/password_resets_controller.rb'

####### Metrics #######

####### Layout ########

# privateメゾッドはインデントを通常より深くしたい
Layout/AccessModifierIndentation:
  Exclude:
    - 'app/controllers/users_controller.rb'
    - 'app/models/user.rb'
    - 'app/controllers/password_resets_controller.rb'

# privateメゾッドはインデントを通常より深くしたい
Layout/IndentationConsistency:
  Exclude:
    - 'app/controllers/users_controller.rb'
    - 'app/models/user.rb'
    - 'app/controllers/password_resets_controller.rb'

####### Naming ##############
Naming/PredicateName:
  Exclude:
  -'spec/support/test_helper.rb'