version: '3'
services:
  app:  # rails用コンテナ
    build:
      context: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/uexpress
      - public-data:/uexpress/public
      - tmp-data:/uexpress/tmp
      - log-data:/uexpress/log

  web:   #nginxのコンテナ作成
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/uexpress/public
      - tmp-data:/uexpress/tmp
    ports:
      - "80:80"
    depends_on:
      - app    

volumes:
  mysql_data:
  public-data:
  tmp-data:
  log-data:
