version: '3'

services:
  db:
    image: mysql:8.0.27
    # mysqlログイン時の画面の文字化け防止
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports: 
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql 
    environment:
      MYSQL_DATABASE: UExpress_DB
      MYSQL_ROOT_PASSWORD: Mysql_tomita


  web:   #アプリケーションのコンテナ作成
    build:
      context: .
      dockerfile: Dockerfile
    tty: true 
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/UExpress

volumes:
  mysql_data: