# herokuへのデプロイは、このURL: https://circleci.com/docs/ja/2.0/deployment-integrations/#heroku%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9F%E7%B0%A1%E5%8D%98%E3%81%AA%E4%BE%8B

version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@4.2.0
  heroku: circleci/heroku@1.2.6 # Heroku orbを起動する.デプロイするには、環境変数を設定する必要あり。上URL参照。

workflows:
  heroku_deploy:   # ワークフローの名前
    jobs:
      - build
      - heroku/deploy-via-git: # 事前に設定されたジョブ deploy-via-git を使う
          requires:
            - build
          filters:   #実行するブランチを定義するマップ。https://circleci.com/docs/ja/2.0/configuration-reference/#jobfilters
            branches:
              only: main # onlyで指定したブランチでheroku/deploy-via-gitジョブを実行する(多分).mainにマージしたらデプロイされる(多分)。

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.4-node
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:8.0.27
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_DATABASE: UExpress_app_test
          MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: install chrome browser
          command: |
            sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo apt update
            sudo apt-get install google-chrome-stable
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rubocop-check
      - ruby/rspec-test
